"""
Diagnosis Risk Assistant
========================
Rule-based + lightweight scoring engine that produces a multi-factor clinical
risk assessment from a patient's decrypted record.

This is NOT a clinical decision support system and must NOT be used for
actual medical decisions.  It is provided as a demonstration of how AI/ML
features can overlay on top of the encrypted patient data store.

Risk factors scored:
  • Age
  • Chronic conditions (keyword match)
  • Medications indicating uncontrolled conditions
  • Vital sign ranges (if structured data present)
  • Symptom severity keywords

Output:
  {
    "overall_risk":  "Low" | "Moderate" | "High" | "Critical",
    "risk_score":    float (0–100),
    "factors":       [{"factor": str, "weight": float, "detail": str}, ...],
    "recommendations": [str, ...],
    "disclaimer":    str,
  }
"""

from __future__ import annotations
import re
from dataclasses import dataclass, field
from typing import List, Optional

# ---------------------------------------------------------------------------
# Condition → risk weight mapping
# ---------------------------------------------------------------------------
CONDITION_WEIGHTS = {
    # Cardiovascular
    "heart failure":          18, "myocardial infarction": 18, "coronary artery": 15,
    "atrial fibrillation":    12, "arrhythmia": 10, "hypertension": 8,
    "stroke":                 16, "tia": 12, "deep vein thrombosis": 10,
    "pulmonary embolism":     16,
    # Metabolic
    "diabetes":               10, "obesity": 6, "metabolic syndrome": 8,
    "chronic kidney disease": 15, "renal failure": 18, "dialysis": 20,
    "liver failure":          18, "cirrhosis": 15,
    # Respiratory
    "copd":                   12, "emphysema": 12, "asthma": 6,
    "pneumonia":              10, "pulmonary fibrosis": 14,
    # Oncology
    "cancer":                 20, "carcinoma": 20, "tumor": 15, "malignant": 18,
    "leukemia":               20, "lymphoma": 18, "metastasis": 22,
    # Neurological
    "dementia":               12, "alzheimer": 14, "parkinson": 12,
    "epilepsy":               8,  "neuropathy": 6,
    # Immunological
    "hiv":                    14, "aids": 20, "immunocompromised": 15,
    "lupus":                  12, "rheumatoid": 8,
    # Infection
    "sepsis":                 22, "bacteremia": 18, "tuberculosis": 12,
    "covid":                  8,  "influenza": 4,
    # Psychiatric
    "schizophrenia":           8, "bipolar": 6, "depression": 4,
    "substance abuse":         8, "alcohol": 4,
}

HIGH_RISK_MEDICATIONS = {
    "warfarin", "coumadin", "heparin", "lovenox", "apixaban",
    "rivaroxaban", "dabigatran", "clopidogrel",          # anticoagulants
    "oxycodone", "hydrocodone", "morphine", "fentanyl",   # opioids
    "methotrexate", "cyclophosphamide", "azathioprine",   # immunosuppressants
    "insulin", "glipizide", "glyburide",                  # hypoglycemics
    "digoxin", "amiodarone", "disopyramide",              # antiarrhythmics
    "lithium", "clozapine",                               # narrow therapeutic index
    "tacrolimus", "cyclosporine",                          # transplant drugs
}

SYMPTOM_SEVERITY = {
    "severe":      10, "critical":    15, "extreme":     12,
    "worsening":    6, "deteriorating": 8, "acute":       8,
    "uncontrolled": 7, "refractory":   8,
    "chronic":      4, "persistent":   3, "recurrent":    3,
    "mild":        -2, "improving":   -3, "stable":      -5, "controlled": -4,
}

RECOMMENDATIONS_MAP = {
    "High":     [
        "Schedule immediate specialist review",
        "Review and reconcile all medications",
        "Ensure emergency care plan is documented",
        "Increase monitoring frequency",
    ],
    "Moderate": [
        "Schedule follow-up within 2 weeks",
        "Review medication adherence",
        "Conduct relevant lab work / imaging",
        "Patient education on warning signs",
    ],
    "Low":      [
        "Routine follow-up (3–6 months)",
        "Lifestyle counselling (diet, exercise)",
        "Annual screening panels",
    ],
    "Critical": [
        "⚠️  Immediate escalation required",
        "Consider ICU / urgent admission",
        "Activate emergency care protocol",
        "Notify attending physician immediately",
    ],
}


# ---------------------------------------------------------------------------
# Dataclass
# ---------------------------------------------------------------------------

@dataclass
class RiskFactor:
    factor:  str
    weight:  float
    detail:  str

@dataclass
class RiskAssessment:
    overall_risk:    str
    risk_score:      float
    factors:         List[RiskFactor] = field(default_factory=list)
    recommendations: List[str]        = field(default_factory=list)
    disclaimer: str = (
        "This assessment is generated by an automated rule-based system for "
        "informational purposes only. It does not constitute medical advice "
        "and must not replace clinical judgment."
    )

    def to_dict(self) -> dict:
        return {
            "overall_risk":    self.overall_risk,
            "risk_score":      round(self.risk_score, 1),
            "factors":         [{"factor": f.factor, "weight": f.weight, "detail": f.detail}
                                 for f in self.factors],
            "recommendations": self.recommendations,
            "disclaimer":      self.disclaimer,
        }


# ---------------------------------------------------------------------------
# Engine
# ---------------------------------------------------------------------------

class DiagnosisAssistant:
    """
    Usage:
        ai = DiagnosisAssistant()
        result = ai.assess(
            age=67,
            diagnoses="Hypertension, Type 2 Diabetes, CKD stage 3",
            medications="Metformin 500mg, Lisinopril 10mg, Warfarin 5mg",
            notes="Patient reports worsening oedema and shortness of breath",
            systolic_bp=158,   # optional
            diastolic_bp=95,   # optional
            heart_rate=102,    # optional
            spo2=94.0,         # optional
        )
        result.to_dict()
    """

    # ── Internal helpers ────────────────────────────────────────────────────

    def _age_score(self, age: Optional[int]) -> tuple[float, str]:
        if age is None:
            return 0.0, "Age not provided"
        if age < 18:
            return 2.0, f"Paediatric patient (age {age})"
        if age < 40:
            return 0.0, f"Young adult (age {age})"
        if age < 60:
            return 5.0, f"Middle-aged adult (age {age})"
        if age < 75:
            return 10.0, f"Older adult (age {age})"
        return 18.0, f"Elderly patient (age {age})"

    def _condition_score(self, text: str) -> List[RiskFactor]:
        if not text:
            return []
        lower = text.lower()
        factors = []
        for condition, weight in CONDITION_WEIGHTS.items():
            if condition in lower:
                factors.append(RiskFactor(
                    factor = "Condition",
                    weight = float(weight),
                    detail = condition.title(),
                ))
        return factors

    def _medication_score(self, text: str) -> List[RiskFactor]:
        if not text:
            return []
        lower = text.lower()
        factors = []
        for med in HIGH_RISK_MEDICATIONS:
            if med in lower:
                factors.append(RiskFactor(
                    factor = "High-risk Medication",
                    weight = 5.0,
                    detail = med.title(),
                ))
        # Polypharmacy penalty
        med_count = len(re.findall(r'[A-Za-z]{4,}(?:mg|ml)?', text))
        if med_count > 7:
            factors.append(RiskFactor(
                factor = "Polypharmacy",
                weight = 6.0,
                detail = f"~{med_count} medications listed",
            ))
        return factors

    def _symptom_score(self, text: str) -> List[RiskFactor]:
        if not text:
            return []
        lower = text.lower()
        factors = []
        for term, w in SYMPTOM_SEVERITY.items():
            if term in lower:
                factors.append(RiskFactor(
                    factor = "Symptom Severity",
                    weight = float(w),
                    detail = f"Term detected: '{term}'",
                ))
        return factors

    def _vital_score(self, systolic_bp, diastolic_bp, heart_rate, spo2) -> List[RiskFactor]:
        factors = []
        if systolic_bp is not None:
            if systolic_bp >= 180:
                factors.append(RiskFactor("Vital Sign", 15.0, f"Hypertensive crisis: SBP {systolic_bp}"))
            elif systolic_bp >= 140:
                factors.append(RiskFactor("Vital Sign", 7.0,  f"Elevated BP: SBP {systolic_bp}"))
            elif systolic_bp < 90:
                factors.append(RiskFactor("Vital Sign", 12.0, f"Hypotension: SBP {systolic_bp}"))

        if diastolic_bp is not None:
            if diastolic_bp >= 120:
                factors.append(RiskFactor("Vital Sign", 12.0, f"Hypertensive crisis: DBP {diastolic_bp}"))
            elif diastolic_bp >= 90:
                factors.append(RiskFactor("Vital Sign", 5.0,  f"Elevated DBP: {diastolic_bp}"))

        if heart_rate is not None:
            if heart_rate > 120:
                factors.append(RiskFactor("Vital Sign", 8.0,  f"Tachycardia: HR {heart_rate}"))
            elif heart_rate < 50:
                factors.append(RiskFactor("Vital Sign", 8.0,  f"Bradycardia: HR {heart_rate}"))

        if spo2 is not None:
            if spo2 < 90:
                factors.append(RiskFactor("Vital Sign", 18.0, f"Severe hypoxia: SpO₂ {spo2}%"))
            elif spo2 < 94:
                factors.append(RiskFactor("Vital Sign", 8.0,  f"Low SpO₂: {spo2}%"))

        return factors

    # ── Public API ──────────────────────────────────────────────────────────

    def assess(
        self,
        age:           Optional[int]   = None,
        diagnoses:     str             = "",
        medications:   str             = "",
        notes:         str             = "",
        systolic_bp:   Optional[int]   = None,
        diastolic_bp:  Optional[int]   = None,
        heart_rate:    Optional[int]   = None,
        spo2:          Optional[float] = None,
    ) -> RiskAssessment:

        all_factors: List[RiskFactor] = []

        # Age
        age_w, age_detail = self._age_score(age)
        if age_w != 0:
            all_factors.append(RiskFactor("Age", age_w, age_detail))

        # Conditions, medications, notes, vitals
        all_factors.extend(self._condition_score(diagnoses))
        all_factors.extend(self._medication_score(medications))
        all_factors.extend(self._symptom_score(notes))
        all_factors.extend(self._vital_score(systolic_bp, diastolic_bp, heart_rate, spo2))

        # Total score (clamp to 0–100)
        raw = sum(f.weight for f in all_factors)
        score = max(0.0, min(100.0, raw))

        # Category
        if score >= 60:
            level = "Critical"
        elif score >= 35:
            level = "High"
        elif score >= 15:
            level = "Moderate"
        else:
            level = "Low"

        return RiskAssessment(
            overall_risk    = level,
            risk_score      = score,
            factors         = sorted(all_factors, key=lambda f: -f.weight),
            recommendations = RECOMMENDATIONS_MAP[level],
        )
